/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./scene.gltf -o Gun.jsx -k -K -r public 
Author: FireWarden (https://sketchfab.com/FireWarden)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-m733-954482534e7643398a6e057132cc9f8c
Title: "Low Poly" M733
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useEffect } from 'react'
import { useFrame } from '@react-three/fiber'

export function Weapon(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/model/low_poly_m733/scene.gltf')
  useFrame((state, delta)=>{
    if(group.current){
      group.current.rotation.y += delta
    }
  })
  useEffect(()=>{
    group.current.scale.set(0.01, 0.01,0.01)
  })
  return (
    <group {...props} dispose={null} ref={group}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="360a5ffad7bb47c1abe5ad86eff70f57fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode">
              <group name="M733" position={[0, -40.511, 84.195]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <group name="flash_hider" position={[0, 1.603, 0.529]}>
                  <mesh name="flash_hider_M733_tex_0" geometry={nodes.flash_hider_M733_tex_0.geometry} material={materials.M733_tex} />
                </group>
                <group name="charging_handle" position={[0, 1.786, 0.529]}>
                  <mesh name="charging_handle_M733_tex_0" geometry={nodes.charging_handle_M733_tex_0.geometry} material={materials.M733_tex} />
                </group>
                <group name="handguard_tape" position={[0, 1.689, 0.529]}>
                  <mesh name="handguard_tape_M733_tex_0" geometry={nodes.handguard_tape_M733_tex_0.geometry} material={materials.M733_tex} />
                </group>
                <group name="stock" position={[0, -0.265, 0.529]}>
                  <mesh name="stock_M733_tex_0" geometry={nodes.stock_M733_tex_0.geometry} material={materials.M733_tex} />
                </group>
                <group name="trigger" position={[0, 0.312, 0.301]}>
                  <mesh name="trigger_M733_tex_0" geometry={nodes.trigger_M733_tex_0.geometry} material={materials.M733_tex} />
                </group>
                <group name="silencer" position={[0, 2.35, 0.529]}>
                  <mesh name="silencer_M733_tex_0" geometry={nodes.silencer_M733_tex_0.geometry} material={materials.M733_tex} />
                </group>
                <group name="bolt" position={[0, 0.621, 0.529]}>
                  <mesh name="bolt_M733_tex_0" geometry={nodes.bolt_M733_tex_0.geometry} material={materials.M733_tex} />
                </group>
                <group name="magazine" position={[0, 0.689, 0.054]}>
                  <group name="magazine_tape" position={[0, 0.013, -0.166]}>
                    <mesh name="magazine_tape_M733_tex_0" geometry={nodes.magazine_tape_M733_tex_0.geometry} material={materials.M733_tex} />
                  </group>
                  <mesh name="magazine_M733_tex_0" geometry={nodes.magazine_M733_tex_0.geometry} material={materials.M733_tex} />
                </group>
                <group name="scope" position={[0, 0.71, 1.061]}>
                  <mesh name="scope_M733_tex_0" geometry={nodes.scope_M733_tex_0.geometry} material={materials.M733_tex} />
                </group>
                <mesh name="M733_M733_tex_0" geometry={nodes.M733_M733_tex_0.geometry} material={materials.M733_tex} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model/low_poly_m733/scene.gltf')
